spring:
  application:
    name: ToolVerse Backend
  data:
    mongodb:
      uri: mongodb+srv://vineethnaikeslavath_db_user:hsj7XeL5tRhD3oAu@toolverse.ovqjujb.mongodb.net/?appName=ToolVerse
      database: toolverse

server:
  port: 8080

logging:
  level:
    com.toolverse: DEBUG
    org.springframework.data.mongodb: DEBUG

# JWT Configuration
jwt:
  secret: mySecretKey123456789012345678901234567890
  expiration: 86400000
